services:
  grafanas:
    image: grafana/grafana:10.2.0
    container_name: grafanas
    environment:
      # - GF_LOG_LEVEL=warn
      - VIRTUAL_HOST=${GRAFANA_URL}
      - GF_ANALYTICS_REPORTING_ENABLED=false
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning/
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5123"
        tag: "grafana"
    networks:
      - nginx
  lokis:
    container_name: lokis
    image: grafana/loki:2.9.1
    command: -config.file=/conf/loki-config.yaml
    volumes:
      - ./loki/data:/data
      - ./loki/conf:/conf
    networks:
      - nginx

  vectors:
    image: timberio/vector:0.33.0-debian
    container_name: vectors
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
    ports:
      - "127.0.0.1:5123:5123/udp"
    networks:
      - nginx

networks:
  nginx:
    external: true
